project_id = "ckjevliuwlijfvdjxmmp"

[functions.payfast-webhook]
verify_jwt = false

[functions.payfast-checkout]
verify_jwt = false

[functions.link-subscription]
verify_jwt = false

[functions.get-shared-document]
verify_jwt = false

[functions.submit-partner-application]
verify_jwt = false

[functions.run-commission-month]
verify_jwt = false


[functions.process-email-queue]
verify_jwt = true

[functions.referral-attach]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.payfast-reconcile]
verify_jwt = false
