import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { generateDocument } from "@/lib/documents";

type Profile = {
  owner_user_id: string;
  company_name: string;
  trading_name: string | null;
  registration_number: string | null;
  vat_number: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  postal_code: string | null;
  country: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  website: string | null;
  logo_url: string | null;
  accent_color: string;
  signatory_name: string | null;
  signatory_title: string | null;
};

const empty: Omit<Profile, "owner_user_id"> = {
  company_name: "",
  trading_name: "",
  registration_number: "",
  vat_number: "",
  address_line1: "",
  address_line2: "",
  city: "",
  postal_code: "",
  country: "",
  contact_email: "",
  contact_phone: "",
  website: "",
  logo_url: "",
  accent_color: "#2563eb",
  signatory_name: "",
  signatory_title: "",
};

export default function CompanyProfilePage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [ownerId, setOwnerId] = useState<string | null>(null);
  const [form, setForm] = useState<typeof empty>(empty);
  const [authed, setAuthed] = useState(false);

  useEffect(() => {
    (async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) {
        setLoading(false);
        return;
      }
      setAuthed(true);
      const { data: ownerData } = await supabase.rpc("current_account_owner");
      const owner = ownerData as unknown as string;
      setOwnerId(owner);
      const { data } = await supabase
        .from("company_profiles")
        .select("*")
        .eq("owner_user_id", owner)
        .maybeSingle();
      if (data) {
        setForm({ ...empty, ...(data as unknown as Profile) });
      }
      setLoading(false);
    })();
  }, []);

  const isTeamMember = ownerId && ownerId !== undefined;
  const set = <K extends keyof typeof empty>(k: K, v: (typeof empty)[K]) =>
    setForm((f) => ({ ...f, [k]: v }));

  async function uploadLogo(file: File) {
    if (!ownerId) return;
    const ext = file.name.split(".").pop() || "png";
    const path = `${ownerId}/logo.${ext}`;
    const { error } = await supabase.storage
      .from("company-logos")
      .upload(path, file, { upsert: true, contentType: file.type });
    if (error) {
      toast.error("Couldn't upload that logo. The rest of your profile will still save. (" + error.message + ")");
      return;
    }
    const { data } = supabase.storage.from("company-logos").getPublicUrl(path);
    set("logo_url", data.publicUrl + "?t=" + Date.now());
    toast.success("Logo uploaded");
  }

  function removeLogo() {
    set("logo_url", "");
    toast.success("Logo removed. Remember to save.");
  }

  function resetColor() {
    set("accent_color", "#2563eb");
  }

  async function save() {
    if (!ownerId) return;
    if (!form.company_name.trim()) {
      toast.error("Please enter a company name before saving.");
      return;
    }
    setSaving(true);
    const payload = { ...form, owner_user_id: ownerId };
    const { error } = await supabase
      .from("company_profiles")
      .upsert(payload, { onConflict: "owner_user_id" });
    setSaving(false);
    if (error) toast.error("Save failed: " + error.message);
    else toast.success("Saved — your branding will appear on all new documents.");
  }

  async function generateSample() {
    try {
      const result = await generateDocument({
        type: "sample",
        title: "Sample Document",
        subtitle: "A demonstration of your document house style",
        body: [
          { kind: "p", text: "This is a sample document generated by the app to show how your branding will appear on every document you produce." },
          { kind: "h", text: "House style" },
          { kind: "p", text: "Every document uses the same header, footer and signature layout, so anyone reading something from your company knows immediately where it came from." },
          { kind: "list", items: ["Logo and company name in the header", "Address, contact and page numbers in the footer", "Consistent typography across all documents"] },
        ],
      });
      toast.success("Sample document generated");
      window.open(result.share_url, "_blank");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      if (msg === "company_profile_incomplete") {
        toast.error("Fill in your company name first, then save.");
      } else {
        toast.error("Generation failed: " + msg);
      }
    }
  }

  if (loading) return <AppShell><p className="text-muted-foreground">Loading…</p></AppShell>;
  if (!authed) {
    return (
      <AppShell>
        <Card>
          <CardContent className="p-6 text-center space-y-3">
            <p>You need to sign in to manage your company profile.</p>
            <Button asChild><a href="/">Go to sign in</a></Button>
          </CardContent>
        </Card>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold">Company profile</h1>
          <p className="text-sm text-muted-foreground">
            These details appear on every document the app generates. All documents
            share the same layout so they look like they come from the same employer.
          </p>
        </div>

        <Card>
          <CardHeader><CardTitle>Identity</CardTitle></CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <Field label="Company name *" value={form.company_name} onChange={(v) => set("company_name", v)} />
            <Field label="Trading name" value={form.trading_name || ""} onChange={(v) => set("trading_name", v)} />
            <Field label="Registration number" value={form.registration_number || ""} onChange={(v) => set("registration_number", v)} />
            <Field label="VAT number" value={form.vat_number || ""} onChange={(v) => set("vat_number", v)} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Address & contact</CardTitle></CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <Field label="Address line 1" value={form.address_line1 || ""} onChange={(v) => set("address_line1", v)} />
            <Field label="Address line 2" value={form.address_line2 || ""} onChange={(v) => set("address_line2", v)} />
            <Field label="City" value={form.city || ""} onChange={(v) => set("city", v)} />
            <Field label="Postal code" value={form.postal_code || ""} onChange={(v) => set("postal_code", v)} />
            <Field label="Country" value={form.country || ""} onChange={(v) => set("country", v)} />
            <Field label="Contact email" value={form.contact_email || ""} onChange={(v) => set("contact_email", v)} />
            <Field label="Contact phone" value={form.contact_phone || ""} onChange={(v) => set("contact_phone", v)} />
            <Field label="Website" value={form.website || ""} onChange={(v) => set("website", v)} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Branding</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Logo</Label>
              <div className="flex items-center gap-4 mt-2">
                {form.logo_url && (
                  <img src={form.logo_url} alt="Logo" className="h-16 w-auto rounded border bg-white p-1" />
                )}
                <Input
                  type="file"
                  accept="image/png,image/jpeg"
                  onChange={(e) => e.target.files?.[0] && uploadLogo(e.target.files[0])}
                />
              </div>
            </div>
            <div>
              <Label>Accent colour</Label>
              <div className="flex items-center gap-3 mt-2">
                <input
                  type="color"
                  value={form.accent_color}
                  onChange={(e) => set("accent_color", e.target.value)}
                  className="h-10 w-16 rounded border bg-background"
                />
                <Input value={form.accent_color} onChange={(e) => set("accent_color", e.target.value)} className="w-32" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Default signatory</CardTitle></CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <Field label="Signatory name" value={form.signatory_name || ""} onChange={(v) => set("signatory_name", v)} />
            <Field label="Signatory title" value={form.signatory_title || ""} onChange={(v) => set("signatory_title", v)} />
          </CardContent>
        </Card>

        <div className="flex gap-3">
          <Button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save profile"}</Button>
          <Button variant="outline" onClick={generateSample}>Generate sample document</Button>
        </div>
      </div>
    </AppShell>
  );
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div>
      <Label>{label}</Label>
      <Input className="mt-1" value={value} onChange={(e) => onChange(e.target.value)} />
    </div>
  );
}
